const fetch = require("node-fetch");

const { Command } = require("discord-akairo");
const { CreateEmbed } = require("../../Utility/CreateEmbed");

module.exports = class InspireCommand extends Command {
  constructor() {
    super("inspire", {
      aliases: ["inspire"],
      description: {
        content: "returns a totally not weird inspiring quote generated by ai",
        usage: "inspire",
        example: ["inspire"],
      },
      category: "fun",
      cooldown: 3000,
    });
  }

  /**
   *
   * @param {import('discord.js').Message} msg
   * @returns
   */
  async exec(msg) {
    try {
      const body = await fetch("https://inspirobot.me/api?generate=true");
      const image = await body.text();
      const embed = CreateEmbed("info").setImage(image);
      msg.reply({ embeds: [embed], allowedMentions: { repliedUser: false } });
      // msg.reply({ content: ans });
    } catch (e) {
      this.client.logger.error(e.message);
      msg.channel.send(CreateEmbed("warn", "⛔ | An error occured"));
    }
  }
};
